FROM python:3.10


ENV VAR1=10
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code

RUN apt update && apt install -y netcat-openbsd

# Install python dependencies in /.venv
COPY Pipfile Pipfile.lock ./
RUN python -m pip install --upgrade pip
RUN pip install pipenv 


COPY . /code
RUN pipenv install 