# Generated by Django 4.1 on 2025-08-10 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=200)),
                ('level_category', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=200)),
                ('launch_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('house_number', models.CharField(max_length=200)),
                ('type_shop', models.CharField(choices=[('Factory', 'Factory'), ('Distributor', 'Distributor'), ('Large retail chain', 'Large retail chain'), ('Dealership center', 'Dealership center'), ('Individual entrepreneur', 'Individual entrepreneur')], max_length=50)),
                ('debt_to_supplier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.categorymodel')),
                ('products', models.ManyToManyField(blank=True, to='shop.productmodel')),
            ],
        ),
    ]
